const mongoose = require('mongoose');
// const uniqueValidator = require('mongoose-unique-validator');


const userInfoSchema = mongoose.Schema({
    username: { type: String, required: true},
    name: { type: String },
    bio: { type: String },
    gender: { type: String },
    birthday: { type: String},
    major: { type: String},
    minor: { type: String},
    sport: { type: String},
    club: { type: String},
    pronouns: { type: String},
    CodeCompleted: { type: String},
    CodeCompleted2: { type: String},
    CodeCompleted3: { type: String},
    CodeCompleted4: { type: String},
    CodeCompleted5: { type: String},
    CodeCompleted6: { type: String},
    CodeCompleted7: { type: String},
    CodeCompleted8: { type: String},
    CodeCompleted9: { type: String},
    CodeCompleted10: { type: String},
    CodeCompleted11: { type: String},
    CodeCompleted12: { type: String},
    CodeCompleted13: { type: String},
    CodeCompleted14: { type: String},
    CodeCompleted15: { type: String},
    CodeCompleted16: { type: String},
    CodeCompleted17: { type: String},
    CodeCompleted18: { type: String},
    CodeCompleted19: { type: String},
    CodeCompleted20: { type: String},
    CodeCompleted21: { type: String},
    CodeCompleted22: { type: String},
    CodeCompleted23: { type: String},
    CodeCompleted24: { type: String},
    CodeCompleted25: { type: String},
    CodeCompleted26: { type: String},
    CodeCompleted27: { type: String},
    CodeCompleted28: { type: String},
    CodeCompleted29: { type: String},
    CodeCompleted30: { type: String},
    CodeCompleted31: { type: String},
    CodeCompleted32: { type: String},
    CodeCompleted33: { type: String},
    CodeCompleted34: { type: String},
    CodeCompleted35: { type: String},
    CodeCompleted36: { type: String},
    CodeCompleted37: { type: String},
    CodeCompleted38: { type: String},
    CodeCompleted39: { type: String},
    CodeCompleted40: { type: String},
    CodeCompletedX: { type: String},

    CodePursuing: { type: String},
    CodePursuing2: { type: String},
    CodePursuing3: { type: String},
    CodePursuing4: { type: String},
    CodePursuing5: { type: String},
    CodePursuing6: { type: String},
    CodePursuing7: { type: String},
    CodePursuing8: { type: String},
    CodePursuing9: { type: String},
    CodePursuing10: { type: String},
    CodePursuing11: { type: String},
    CodePursuing12: { type: String},
    CodePursuing13: { type: String},
    CodePursuing14: { type: String},
    ProfilePicPath: { type: String},
    cloudinary_id: { type: String},
    Creator: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true},

 });
 
//  userInfoSchema.plugin(uniqueValidator);
 
 
 module.exports = mongoose.model('UserInfo', userInfoSchema);